"""Release and schema versions used by the compiler and generated artifacts."""

from __future__ import annotations

COMPILER_VERSION = "4.0.1"
WORKBOOK_SCHEMA_VERSION = "4.0.1"
DEFAULT_DATA_PRODUCT_VERSION = "1.0.0"
DEFAULT_TOOLKIT_REVISION = "v4.0.1"
DET_SPEC_VERSION = "det/v4.0.1"
ODCS_VERSION = "3.1.0"
OPERATOR_REGISTRY_VERSION = "4.0.1"


def generated_header(comment: str) -> str:
    """Return the standard generated-file ownership header."""

    return f"{comment} Generated by det {COMPILER_VERSION}. Edit the workbook, not this file.\n"
