-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.
-- Source contract: urn:datacontract:customer:customer_360@1.0.0 (model: stg_customers)
{{ config(meta={"datacontract_cli": {"check": "stg_customers__row_count", "contract_versions": ["1.0.0"], "generated": true, "include_in_tests": true, "model": "stg_customers", "description": "The published customer product must contain rows"}}) }}
WITH _dc_metric (metric_value) AS (
SELECT COUNT(*) FROM {{ ref('stg_customers') }}
)
SELECT metric_value FROM _dc_metric WHERE metric_value IS NULL OR metric_value <= 0
