"""Mapped-field coverage, grain, audit, and enforced-contract validation."""

from __future__ import annotations

from ...adapters import AdapterRegistry
from ...errors import DiagnosticCategory
from ...models import FailureMode, SchemaImplementation
from .context import ValidationContext

AUDIT_FIELDS = {"_det_loaded_at", "_det_invocation_id", "_det_source_system"}


class ModelOutputValidator:
    def __init__(self, adapters: AdapterRegistry | None = None) -> None:
        self.adapters = adapters or AdapterRegistry.default()

    def validate(self, context: ValidationContext) -> None:
        spec = context.spec
        for rule in spec.rules:
            context.rules_by_model[rule.model].append(rule)

        for model in spec.models:
            if not model.enabled:
                continue
            mapped_fields = {item.target_field for item in context.mappings_by_model[model.name]}
            declared_mapped = {
                item.name
                for item in spec.schema_properties
                if item.object_name == model.name
                and item.implementation == SchemaImplementation.MAPPED
            }
            for field in sorted(declared_mapped - mapped_fields):
                prop = context.schema[(model.name, field)]
                context.add(
                    "DET-MOD-007",
                    DiagnosticCategory.MODEL,
                    prop.workbook_sheet or f"Schema {model.name}",
                    prop.workbook_row,
                    f"{model.name}.{field} is declared as mapped but has no DET Mapping implementation",
                )
            for grain in model.grain:
                if grain not in mapped_fields:
                    context.add(
                        "DET-MOD-008",
                        DiagnosticCategory.MODEL,
                        "DET Models",
                        None,
                        f"{model.name} grain field {grain!r} is not mapped",
                    )

            rejection_fields: set[str] = set()
            if any(
                item.failure == FailureMode.REJECT for item in context.rules_by_model[model.name]
            ):
                rejection_fields.add("_det_rejections")
            if any(item.failure == FailureMode.WARN for item in context.rules_by_model[model.name]):
                rejection_fields.add("_det_warnings")
            declared_audit = {
                item.name
                for item in spec.schema_properties
                if item.object_name == model.name
                and item.implementation == SchemaImplementation.AUDIT
            }
            declared_system = {
                item.name
                for item in spec.schema_properties
                if item.object_name == model.name
                and item.implementation == SchemaImplementation.SYSTEM_GENERATED
            }
            generated_audit_fields = AUDIT_FIELDS - (
                {"_det_source_system"} if not model.audit_source else set()
            )
            for field in sorted(declared_audit - generated_audit_fields):
                context.add(
                    "DET-MOD-009",
                    DiagnosticCategory.MODEL,
                    f"Schema {model.name}",
                    None,
                    f"audit field {field!r} is not generated by this model",
                )
            for field in sorted(declared_system - rejection_fields):
                context.add(
                    "DET-MOD-010",
                    DiagnosticCategory.MODEL,
                    f"Schema {model.name}",
                    None,
                    f"unknown system-generated field {field!r}",
                )
            if model.enforce_contract:
                missing_operational = (generated_audit_fields | rejection_fields) - (
                    declared_audit | declared_system
                )
                if missing_operational:
                    context.add(
                        "DET-MOD-011",
                        DiagnosticCategory.MODEL,
                        f"Schema {model.name}",
                        None,
                        "enforced contract is missing generated fields: "
                        + ", ".join(sorted(missing_operational)),
                        "Add them as DET Implementation audit or system-generated.",
                    )
                provider = self.adapters.get(spec.build.adapter)
                if provider is not None:
                    self._validate_operational_types(
                        context,
                        model.name,
                        generated_audit_fields | rejection_fields,
                        provider.operational_types,
                        provider.display_name,
                    )

    @staticmethod
    def _validate_operational_types(
        context: ValidationContext,
        model_name: str,
        fields: set[str],
        expected_types: dict[str, str],
        adapter_name: str,
    ) -> None:
        for field in sorted(item for item in fields if item is not None):
            prop = context.schema.get((model_name, field))
            actual = (prop.physical_type or "").strip().casefold() if prop else ""
            if prop and actual != expected_types[field]:
                context.add(
                    "DET-MOD-012",
                    DiagnosticCategory.MODEL,
                    prop.workbook_sheet or f"Schema {model_name}",
                    prop.workbook_row,
                    f"{model_name}.{field}: {adapter_name} contract type must be "
                    f"{expected_types[field]!r}",
                    "Set the Schema Physical Type to the actual generated expression type.",
                )
