{# Generated by scripts/generate_alias_facade.py. Do not edit. #}
{# Every public macro delegates to the canonical package namespace. #}

{% macro assertions(column=none) -%}
  {{ return(dbt_data_engineering_toolkit.assertions(column=column)) }}
{%- endmacro %}

{% macro assertions_filter(column=none, exclude_list=none, include_list=none, reverse=false) -%}
  {{ return(dbt_data_engineering_toolkit.assertions_filter(column=column, exclude_list=exclude_list, include_list=include_list, reverse=reverse)) }}
{%- endmacro %}

{% macro audit_columns(source_system=none, loaded_at_expression=none, prefix='_det_') -%}
  {{ return(dbt_data_engineering_toolkit.audit_columns(source_system=source_system, loaded_at_expression=loaded_at_expression, prefix=prefix)) }}
{%- endmacro %}

{% macro bin_numeric(expression, edges, labels=none, right=true, include_lowest=false) -%}
  {{ return(dbt_data_engineering_toolkit.bin_numeric(expression=expression, edges=edges, labels=labels, right=right, include_lowest=include_lowest)) }}
{%- endmacro %}

{% macro clean_boolean(expression, true_values=['true', 't', 'yes', 'y', '1'], false_values=['false', 'f', 'no', 'n', '0']) -%}
  {{ return(dbt_data_engineering_toolkit.clean_boolean(expression=expression, true_values=true_values, false_values=false_values)) }}
{%- endmacro %}

{% macro clean_code(expression, remove_prefix=none, remove_suffix=none, case='upper', corrections={}, blank_as_null=true) -%}
  {{ return(dbt_data_engineering_toolkit.clean_code(expression=expression, remove_prefix=remove_prefix, remove_suffix=remove_suffix, case=case, corrections=corrections, blank_as_null=blank_as_null)) }}
{%- endmacro %}

{% macro clean_date(expression) -%}
  {{ return(dbt_data_engineering_toolkit.clean_date(expression=expression)) }}
{%- endmacro %}

{% macro clean_email(expression) -%}
  {{ return(dbt_data_engineering_toolkit.clean_email(expression=expression)) }}
{%- endmacro %}

{% macro clean_integer(expression) -%}
  {{ return(dbt_data_engineering_toolkit.clean_integer(expression=expression)) }}
{%- endmacro %}

{% macro clean_numeric(expression, precision=38, scale=6) -%}
  {{ return(dbt_data_engineering_toolkit.clean_numeric(expression=expression, precision=precision, scale=scale)) }}
{%- endmacro %}

{% macro clean_phone(expression, keep_plus=true) -%}
  {{ return(dbt_data_engineering_toolkit.clean_phone(expression=expression, keep_plus=keep_plus)) }}
{%- endmacro %}

{% macro clean_string(expression, trim=true, collapse_whitespace=true, case='preserve', blank_as_null=true) -%}
  {{ return(dbt_data_engineering_toolkit.clean_string(expression=expression, trim=trim, collapse_whitespace=collapse_whitespace, case=case, blank_as_null=blank_as_null)) }}
{%- endmacro %}

{% macro clean_timestamp(expression) -%}
  {{ return(dbt_data_engineering_toolkit.clean_timestamp(expression=expression)) }}
{%- endmacro %}

{% macro clip(expression, lower, upper) -%}
  {{ return(dbt_data_engineering_toolkit.clip(expression=expression, lower=lower, upper=upper)) }}
{%- endmacro %}

{% macro convert_value(expression, data_type) -%}
  {{ return(dbt_data_engineering_toolkit.convert_value(expression=expression, data_type=data_type)) }}
{%- endmacro %}

{% macro correct_errors(expression, correction_map) -%}
  {{ return(dbt_data_engineering_toolkit.correct_errors(expression=expression, correction_map=correction_map)) }}
{%- endmacro %}

{% macro date_spine(datepart, start_date, end_date) -%}
  {{ return(dbt_data_engineering_toolkit.date_spine(datepart=datepart, start_date=start_date, end_date=end_date)) }}
{%- endmacro %}

{% macro deduplicate(relation, partition_by, order_by) -%}
  {{ return(dbt_data_engineering_toolkit.deduplicate(relation=relation, partition_by=partition_by, order_by=order_by)) }}
{%- endmacro %}

{% macro distinct_rows(relation) -%}
  {{ return(dbt_data_engineering_toolkit.distinct_rows(relation=relation)) }}
{%- endmacro %}

{% macro drop_missing_rows(relation, columns) -%}
  {{ return(dbt_data_engineering_toolkit.drop_missing_rows(relation=relation, columns=columns)) }}
{%- endmacro %}

{% macro fill_missing(expression, value) -%}
  {{ return(dbt_data_engineering_toolkit.fill_missing(expression=expression, value=value)) }}
{%- endmacro %}

{% macro format_date(expression, pattern='%Y-%m-%d', null_value=none) -%}
  {{ return(dbt_data_engineering_toolkit.format_date(expression=expression, pattern=pattern, null_value=null_value)) }}
{%- endmacro %}

{% macro format_number(expression, decimal_places=none, grouping=false, prefix='', suffix='', null_value=none) -%}
  {{ return(dbt_data_engineering_toolkit.format_number(expression=expression, decimal_places=decimal_places, grouping=grouping, prefix=prefix, suffix=suffix, null_value=null_value)) }}
{%- endmacro %}

{% macro format_string(expression, case='preserve', trim=false, collapse_whitespace=false, blank_as_null=false, null_value=none) -%}
  {{ return(dbt_data_engineering_toolkit.format_string(expression=expression, case=case, trim=trim, collapse_whitespace=collapse_whitespace, blank_as_null=blank_as_null, null_value=null_value)) }}
{%- endmacro %}

{% macro format_temporal(expression, data_type, pattern='%Y-%m-%d') -%}
  {{ return(dbt_data_engineering_toolkit.format_temporal(expression=expression, data_type=data_type, pattern=pattern)) }}
{%- endmacro %}

{% macro format_timestamp(expression, pattern='%Y-%m-%d %H:%M:%S', null_value=none) -%}
  {{ return(dbt_data_engineering_toolkit.format_timestamp(expression=expression, pattern=pattern, null_value=null_value)) }}
{%- endmacro %}

{% macro format_value(expression, data_type, formatting=none) -%}
  {{ return(dbt_data_engineering_toolkit.format_value(expression=expression, data_type=data_type, formatting=formatting)) }}
{%- endmacro %}

{% macro is_between(expression, min_value=none, max_value=none, inclusive=true, allow_null=false) -%}
  {{ return(dbt_data_engineering_toolkit.is_between(expression=expression, min_value=min_value, max_value=max_value, inclusive=inclusive, allow_null=allow_null)) }}
{%- endmacro %}

{% macro is_email(expression, allow_null=false) -%}
  {{ return(dbt_data_engineering_toolkit.is_email(expression=expression, allow_null=allow_null)) }}
{%- endmacro %}

{% macro is_in_list(expression, values, allow_null=false, case_sensitive=true) -%}
  {{ return(dbt_data_engineering_toolkit.is_in_list(expression=expression, values=values, allow_null=allow_null, case_sensitive=case_sensitive)) }}
{%- endmacro %}

{% macro is_iqr_anomaly(expression, q1_expression, q3_expression, threshold=1.5) -%}
  {{ return(dbt_data_engineering_toolkit.is_iqr_anomaly(expression=expression, q1_expression=q1_expression, q3_expression=q3_expression, threshold=threshold)) }}
{%- endmacro %}

{% macro is_modified_zscore_anomaly(expression, median_expression, mad_expression, threshold=3.5) -%}
  {{ return(dbt_data_engineering_toolkit.is_modified_zscore_anomaly(expression=expression, median_expression=median_expression, mad_expression=mad_expression, threshold=threshold)) }}
{%- endmacro %}

{% macro is_positive(expression, allow_null=false) -%}
  {{ return(dbt_data_engineering_toolkit.is_positive(expression=expression, allow_null=allow_null)) }}
{%- endmacro %}

{% macro is_zscore_anomaly(expression, threshold=3, partition_by=none) -%}
  {{ return(dbt_data_engineering_toolkit.is_zscore_anomaly(expression=expression, threshold=threshold, partition_by=partition_by)) }}
{%- endmacro %}

{% macro keep_quarantined_rows(column=none) -%}
  {{ return(dbt_data_engineering_toolkit.keep_quarantined_rows(column=column)) }}
{%- endmacro %}

{% macro keep_valid_rows(column=none) -%}
  {{ return(dbt_data_engineering_toolkit.keep_valid_rows(column=column)) }}
{%- endmacro %}

{% macro key_value_map(expression, mapping, default=none, preserve_unmapped=false, data_type=none, formatting=none, case_sensitive=true) -%}
  {{ return(dbt_data_engineering_toolkit.key_value_map(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, data_type=data_type, formatting=formatting, case_sensitive=case_sensitive)) }}
{%- endmacro %}

{% macro label_encode(expression, categories, unknown=none) -%}
  {{ return(dbt_data_engineering_toolkit.label_encode(expression=expression, categories=categories, unknown=unknown)) }}
{%- endmacro %}

{% macro log_transform(expression, offset=1) -%}
  {{ return(dbt_data_engineering_toolkit.log_transform(expression=expression, offset=offset)) }}
{%- endmacro %}

{% macro map_boolean(expression, mapping, default=none, preserve_unmapped=false, case_sensitive=true, true_values=['true', 't', 'yes', 'y', '1'], false_values=['false', 'f', 'no', 'n', '0']) -%}
  {{ return(dbt_data_engineering_toolkit.map_boolean(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, case_sensitive=case_sensitive, true_values=true_values, false_values=false_values)) }}
{%- endmacro %}

{% macro map_date(expression, mapping, default=none, preserve_unmapped=false, case_sensitive=true) -%}
  {{ return(dbt_data_engineering_toolkit.map_date(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, case_sensitive=case_sensitive)) }}
{%- endmacro %}

{% macro map_integer(expression, mapping, default=none, preserve_unmapped=false, case_sensitive=true) -%}
  {{ return(dbt_data_engineering_toolkit.map_integer(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, case_sensitive=case_sensitive)) }}
{%- endmacro %}

{% macro map_numeric(expression, mapping, default=none, preserve_unmapped=false, case_sensitive=true, precision=38, scale=6) -%}
  {{ return(dbt_data_engineering_toolkit.map_numeric(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, case_sensitive=case_sensitive, precision=precision, scale=scale)) }}
{%- endmacro %}

{% macro map_string(expression, mapping, default=none, preserve_unmapped=false, case_sensitive=true, case='preserve', trim=false, collapse_whitespace=false, blank_as_null=false) -%}
  {{ return(dbt_data_engineering_toolkit.map_string(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, case_sensitive=case_sensitive, case=case, trim=trim, collapse_whitespace=collapse_whitespace, blank_as_null=blank_as_null)) }}
{%- endmacro %}

{% macro map_timestamp(expression, mapping, default=none, preserve_unmapped=false, case_sensitive=true) -%}
  {{ return(dbt_data_engineering_toolkit.map_timestamp(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, case_sensitive=case_sensitive)) }}
{%- endmacro %}

{% macro map_value(expression, mapping, default=none, preserve_unmapped=false, data_type=none, formatting=none, case_sensitive=true) -%}
  {{ return(dbt_data_engineering_toolkit.map_value(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, data_type=data_type, formatting=formatting, case_sensitive=case_sensitive)) }}
{%- endmacro %}

{% macro mapping(expression, mapping, default=none, preserve_unmapped=false, data_type=none, format=none, case_sensitive=true) -%}
  {{ return(dbt_data_engineering_toolkit.mapping(expression=expression, mapping=mapping, default=default, preserve_unmapped=preserve_unmapped, data_type=data_type, format=format, case_sensitive=case_sensitive)) }}
{%- endmacro %}

{% macro mask_hash(expression, salt_expression=none) -%}
  {{ return(dbt_data_engineering_toolkit.mask_hash(expression=expression, salt_expression=salt_expression)) }}
{%- endmacro %}

{% macro mask_redact(expression, replacement='[REDACTED]', preserve_null=true) -%}
  {{ return(dbt_data_engineering_toolkit.mask_redact(expression=expression, replacement=replacement, preserve_null=preserve_null)) }}
{%- endmacro %}

{% macro min_max_scale(expression, partition_by=none, zero_range_value=0) -%}
  {{ return(dbt_data_engineering_toolkit.min_max_scale(expression=expression, partition_by=partition_by, zero_range_value=zero_range_value)) }}
{%- endmacro %}

{% macro multi_hot(expression, categories, delimiter='|', prefix='token') -%}
  {{ return(dbt_data_engineering_toolkit.multi_hot(expression=expression, categories=categories, delimiter=delimiter, prefix=prefix)) }}
{%- endmacro %}

{% macro normalize_whitespace(expression) -%}
  {{ return(dbt_data_engineering_toolkit.normalize_whitespace(expression=expression)) }}
{%- endmacro %}

{% macro null_if_blank(expression) -%}
  {{ return(dbt_data_engineering_toolkit.null_if_blank(expression=expression)) }}
{%- endmacro %}

{% macro one_hot(expression, categories, prefix='category') -%}
  {{ return(dbt_data_engineering_toolkit.one_hot(expression=expression, categories=categories, prefix=prefix)) }}
{%- endmacro %}

{% macro percentile(expression, percentile, partition_by=none) -%}
  {{ return(dbt_data_engineering_toolkit.percentile(expression=expression, percentile=percentile, partition_by=partition_by)) }}
{%- endmacro %}

{% macro regex_match(expression, pattern) -%}
  {{ return(dbt_data_engineering_toolkit.regex_match(expression=expression, pattern=pattern)) }}
{%- endmacro %}

{% macro regex_replace_all(expression, pattern, replacement='') -%}
  {{ return(dbt_data_engineering_toolkit.regex_replace_all(expression=expression, pattern=pattern, replacement=replacement)) }}
{%- endmacro %}

{% macro replace_outside_bounds(expression, lower, upper, replacement) -%}
  {{ return(dbt_data_engineering_toolkit.replace_outside_bounds(expression=expression, lower=lower, upper=upper, replacement=replacement)) }}
{%- endmacro %}

{% macro rule_compare(left, operator, right, allow_null=false) -%}
  {{ return(dbt_data_engineering_toolkit.rule_compare(left=left, operator=operator, right=right, allow_null=allow_null)) }}
{%- endmacro %}

{% macro rule_date_order(start_date, end_date, allow_null=false) -%}
  {{ return(dbt_data_engineering_toolkit.rule_date_order(start_date=start_date, end_date=end_date, allow_null=allow_null)) }}
{%- endmacro %}

{% macro rule_one_of(expressions) -%}
  {{ return(dbt_data_engineering_toolkit.rule_one_of(expressions=expressions)) }}
{%- endmacro %}

{% macro rule_required_when(required_expression, when_expression) -%}
  {{ return(dbt_data_engineering_toolkit.rule_required_when(required_expression=required_expression, when_expression=when_expression)) }}
{%- endmacro %}

{% macro rule_sum_equals(total, components, tolerance=0, allow_null=false) -%}
  {{ return(dbt_data_engineering_toolkit.rule_sum_equals(total=total, components=components, tolerance=tolerance, allow_null=allow_null)) }}
{%- endmacro %}

{% macro safe_add(fields) -%}
  {{ return(dbt_data_engineering_toolkit.safe_add(fields=fields)) }}
{%- endmacro %}

{% macro safe_divide(numerator, denominator) -%}
  {{ return(dbt_data_engineering_toolkit.safe_divide(numerator=numerator, denominator=denominator)) }}
{%- endmacro %}

{% macro safe_subtract(fields) -%}
  {{ return(dbt_data_engineering_toolkit.safe_subtract(fields=fields)) }}
{%- endmacro %}

{% macro standard_score(expression, partition_by=none, zero_variance_value=none) -%}
  {{ return(dbt_data_engineering_toolkit.standard_score(expression=expression, partition_by=partition_by, zero_variance_value=zero_variance_value)) }}
{%- endmacro %}

{% macro standardize_code(expression, aliases={}, length=none) -%}
  {{ return(dbt_data_engineering_toolkit.standardize_code(expression=expression, aliases=aliases, length=length)) }}
{%- endmacro %}

{% macro standardize_country(expression, aliases={}) -%}
  {{ return(dbt_data_engineering_toolkit.standardize_country(expression=expression, aliases=aliases)) }}
{%- endmacro %}

{% macro standardize_currency(expression, aliases={}) -%}
  {{ return(dbt_data_engineering_toolkit.standardize_currency(expression=expression, aliases=aliases)) }}
{%- endmacro %}

{% macro string_capitalize(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_capitalize(expression=expression)) }}
{%- endmacro %}

{% macro string_casefold(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_casefold(expression=expression)) }}
{%- endmacro %}

{% macro string_center(expression, width, fillchar=' ') -%}
  {{ return(dbt_data_engineering_toolkit.string_center(expression=expression, width=width, fillchar=fillchar)) }}
{%- endmacro %}

{% macro string_left_strip(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_left_strip(expression=expression)) }}
{%- endmacro %}

{% macro string_ljust(expression, width, fillchar=' ') -%}
  {{ return(dbt_data_engineering_toolkit.string_ljust(expression=expression, width=width, fillchar=fillchar)) }}
{%- endmacro %}

{% macro string_lower(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_lower(expression=expression)) }}
{%- endmacro %}

{% macro string_pad(expression, width, side='both', fillchar=' ') -%}
  {{ return(dbt_data_engineering_toolkit.string_pad(expression=expression, width=width, side=side, fillchar=fillchar)) }}
{%- endmacro %}

{% macro string_regex_extract(expression, pattern, group=1) -%}
  {{ return(dbt_data_engineering_toolkit.string_regex_extract(expression=expression, pattern=pattern, group=group)) }}
{%- endmacro %}

{% macro string_regex_extract_all(expression, pattern, group=1) -%}
  {{ return(dbt_data_engineering_toolkit.string_regex_extract_all(expression=expression, pattern=pattern, group=group)) }}
{%- endmacro %}

{% macro string_regex_replace_many(expression, replacements) -%}
  {{ return(dbt_data_engineering_toolkit.string_regex_replace_many(expression=expression, replacements=replacements)) }}
{%- endmacro %}

{% macro string_remove_all_whitespace(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_remove_all_whitespace(expression=expression)) }}
{%- endmacro %}

{% macro string_remove_prefix(expression, prefix) -%}
  {{ return(dbt_data_engineering_toolkit.string_remove_prefix(expression=expression, prefix=prefix)) }}
{%- endmacro %}

{% macro string_remove_punctuation(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_remove_punctuation(expression=expression)) }}
{%- endmacro %}

{% macro string_remove_suffix(expression, suffix) -%}
  {{ return(dbt_data_engineering_toolkit.string_remove_suffix(expression=expression, suffix=suffix)) }}
{%- endmacro %}

{% macro string_remove_whitespace(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_remove_whitespace(expression=expression)) }}
{%- endmacro %}

{% macro string_replace_many(expression, replacements) -%}
  {{ return(dbt_data_engineering_toolkit.string_replace_many(expression=expression, replacements=replacements)) }}
{%- endmacro %}

{% macro string_right_strip(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_right_strip(expression=expression)) }}
{%- endmacro %}

{% macro string_rjust(expression, width, fillchar=' ') -%}
  {{ return(dbt_data_engineering_toolkit.string_rjust(expression=expression, width=width, fillchar=fillchar)) }}
{%- endmacro %}

{% macro string_slice(expression, start=none, stop=none) -%}
  {{ return(dbt_data_engineering_toolkit.string_slice(expression=expression, start=start, stop=stop)) }}
{%- endmacro %}

{% macro string_slice_replace(expression, start=none, stop=none, replacement='') -%}
  {{ return(dbt_data_engineering_toolkit.string_slice_replace(expression=expression, start=start, stop=stop, replacement=replacement)) }}
{%- endmacro %}

{% macro string_split_part(expression, delimiter=',', part=1) -%}
  {{ return(dbt_data_engineering_toolkit.string_split_part(expression=expression, delimiter=delimiter, part=part)) }}
{%- endmacro %}

{% macro string_strip(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_strip(expression=expression)) }}
{%- endmacro %}

{% macro string_title(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_title(expression=expression)) }}
{%- endmacro %}

{% macro string_translate_chars(expression, translations) -%}
  {{ return(dbt_data_engineering_toolkit.string_translate_chars(expression=expression, translations=translations)) }}
{%- endmacro %}

{% macro string_upper(expression) -%}
  {{ return(dbt_data_engineering_toolkit.string_upper(expression=expression)) }}
{%- endmacro %}

{% macro string_zfill(expression, width) -%}
  {{ return(dbt_data_engineering_toolkit.string_zfill(expression=expression, width=width)) }}
{%- endmacro %}

{% macro surrogate_key(fields) -%}
  {{ return(dbt_data_engineering_toolkit.surrogate_key(fields=fields)) }}
{%- endmacro %}

{% macro trim_rows(relation, order_by, start_row=0, end_row=none) -%}
  {{ return(dbt_data_engineering_toolkit.trim_rows(relation=relation, order_by=order_by, start_row=start_row, end_row=end_row)) }}
{%- endmacro %}

{% macro try_cast(expression, data_type) -%}
  {{ return(dbt_data_engineering_toolkit.try_cast(expression=expression, data_type=data_type)) }}
{%- endmacro %}

{% macro undersample_classes(relation, target_column, order_by) -%}
  {{ return(dbt_data_engineering_toolkit.undersample_classes(relation=relation, target_column=target_column, order_by=order_by)) }}
{%- endmacro %}

{% macro unicode_normalize(expression, form='NFC') -%}
  {{ return(dbt_data_engineering_toolkit.unicode_normalize(expression=expression, form=form)) }}
{%- endmacro %}

{% macro union_relations(relations, column_override=none, include=none, exclude=none, source_column_name='_dbt_source_relation', where=none) -%}
  {{ return(dbt_data_engineering_toolkit.union_relations(relations=relations, column_override=column_override, include=include, exclude=exclude, source_column_name=source_column_name, where=where)) }}
{%- endmacro %}

{% macro winsorize(expression, lower_bound, upper_bound) -%}
  {{ return(dbt_data_engineering_toolkit.winsorize(expression=expression, lower_bound=lower_bound, upper_bound=upper_bound)) }}
{%- endmacro %}

{% macro within_bounds(expression, lower, upper, allow_null=false) -%}
  {{ return(dbt_data_engineering_toolkit.within_bounds(expression=expression, lower=lower, upper=upper, allow_null=allow_null)) }}
{%- endmacro %}
