{# Generated by scripts/generate_alias_facade.py. Do not edit. #}

{% test correlation_above(model, column_name, target_column, minimum=0.2) %}
  {{ dbt_data_engineering_toolkit.test_correlation_above(model=model, column_name=column_name, target_column=target_column, minimum=minimum) }}
{% endtest %}

{% test correlation_below(model, column_name, compare_column, maximum=0.8) %}
  {{ dbt_data_engineering_toolkit.test_correlation_below(model=model, column_name=column_name, compare_column=compare_column, maximum=maximum) }}
{% endtest %}

{% test expression_true(model, expression) %}
  {{ dbt_data_engineering_toolkit.test_expression_true(model=model, expression=expression) }}
{% endtest %}

{% test minimum_variance(model, column_name, threshold=0) %}
  {{ dbt_data_engineering_toolkit.test_minimum_variance(model=model, column_name=column_name, threshold=threshold) }}
{% endtest %}

{% test no_future_dates(model, column_name, allow_null=true) %}
  {{ dbt_data_engineering_toolkit.test_no_future_dates(model=model, column_name=column_name, allow_null=allow_null) }}
{% endtest %}

{% test valid_email(model, column_name, allow_null=false) %}
  {{ dbt_data_engineering_toolkit.test_valid_email(model=model, column_name=column_name, allow_null=allow_null) }}
{% endtest %}
