#!/usr/bin/env python3
"""Generate the ``de_toolkit`` namespace from canonical public macro signatures."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL_MACROS = ROOT / "dbt" / "macros"
FACADE = ROOT / "aliases" / "de_toolkit" / "macros" / "facade.sql"
TESTS = ROOT / "aliases" / "de_toolkit" / "macros" / "tests.sql"
MACRO_PATTERN = re.compile(
    r"\{%\s*macro\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\((?P<signature>.*?)\)\s*-?%\}",
    re.DOTALL,
)
TEST_PATTERN = re.compile(
    r"\{%\s*test\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\((?P<signature>.*?)\)\s*-?%\}",
    re.DOTALL,
)


@dataclass(frozen=True, slots=True, order=True)
class Definition:
    name: str
    signature: str
    arguments: tuple[str, ...]


def _arguments(signature: str) -> tuple[str, ...]:
    arguments: list[str] = []
    current: list[str] = []
    depth = 0
    quote: str | None = None
    previous = ""
    for character in signature:
        if quote:
            if character == quote and previous != "\\":
                quote = None
        elif character in {"'", '"'}:
            quote = character
        elif character in "[{(":
            depth += 1
        elif character in "]})":
            depth -= 1
        if character == "," and depth == 0 and quote is None:
            arguments.append("".join(current).split("=", 1)[0].strip())
            current = []
        else:
            current.append(character)
        previous = character
    if "".join(current).strip():
        arguments.append("".join(current).split("=", 1)[0].strip())
    return tuple(arguments)


def _definitions(pattern: re.Pattern[str]) -> list[Definition]:
    definitions: dict[str, Definition] = {}
    for path in sorted(CANONICAL_MACROS.rglob("*.sql")):
        if "private" in path.parts:
            continue
        source = path.read_text(encoding="utf-8")
        for match in pattern.finditer(source):
            name = match.group("name")
            if name.startswith("_") or "__" in name:
                continue
            signature = " ".join(match.group("signature").split())
            definition = Definition(name, signature, _arguments(signature))
            previous = definitions.get(name)
            if previous and previous.signature != signature:
                raise ValueError(
                    f"Public macro {name!r} has conflicting signatures: "
                    f"{previous.signature!r} and {signature!r}"
                )
            definitions[name] = definition
    return sorted(definitions.values())


def render_facade() -> str:
    sections = [
        "{# Generated by scripts/generate_alias_facade.py. Do not edit. #}",
        "{# Every public macro delegates to the canonical package namespace. #}",
        "",
    ]
    for definition in _definitions(MACRO_PATTERN):
        arguments = ", ".join(f"{name}={name}" for name in definition.arguments)
        sections.extend(
            [
                f"{{% macro {definition.name}({definition.signature}) -%}}",
                f"  {{{{ return(dbt_data_engineering_toolkit.{definition.name}({arguments})) }}}}",
                "{%- endmacro %}",
                "",
            ]
        )
    return "\n".join(sections).rstrip() + "\n"


def render_tests() -> str:
    sections = [
        "{# Generated by scripts/generate_alias_facade.py. Do not edit. #}",
        "",
    ]
    for definition in _definitions(TEST_PATTERN):
        arguments = ", ".join(f"{name}={name}" for name in definition.arguments)
        sections.extend(
            [
                f"{{% test {definition.name}({definition.signature}) %}}",
                f"  {{{{ dbt_data_engineering_toolkit.test_{definition.name}({arguments}) }}}}",
                "{% endtest %}",
                "",
            ]
        )
    return "\n".join(sections).rstrip() + "\n"


def generate(*, check: bool = False) -> list[Path]:
    changed: list[Path] = []
    for path, expected in ((FACADE, render_facade()), (TESTS, render_tests())):
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != expected:
            changed.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8", newline="\n")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = generate(check=args.check)
    if args.check and changed:
        for path in changed:
            print(f"Generated facade is stale: {path.relative_to(ROOT)}")
        return 1
    for path in changed:
        print(f"Generated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
